
### HELLO WORLD
GET http://localhost:3000/

### LISTAR TODAS AS CATEGORIAS
GET http://localhost:3000/inventory/categories/

### BUSCAR CATEGORIA PELO ID
GET http://localhost:3000/inventory/categories/3b402dd5-a1fe-4b09-b7f8-6560d071abc5


### CRIAR NOVA CATEGORIA
POST http://localhost:3000/inventory/categories/
Content-Type: application/json

{
    "name":"LANCHES"
}

### ATUALIZAR CATEGORIA
PUT http://localhost:3000/inventory/categories/3b402dd5-a1fe-4b09-b7f8-6560d071abc5
Content-Type: application/json

{
    "name":"REFRIGERANTES",
    "enable":false,
    "show_menu":false
}

### DELETAR CATEGORIA
DELETE  http://localhost:3000/inventory/categories/3b402dd5-a1fe-4b09-b7f8-6560d071abc5


### CADASTRAR PRODUTO
POST http://localhost:3000/inventory/products
Content-Type: application/json

{
    "category_id":"3b402dd5-a1fe-4b09-b7f8-6560d071abc5",
    "name":"FANTA UVA LATA 350ML",
    "price": 3.50
}

### LISTAR TODOS OS PRODUTOS
GET http://localhost:3000/inventory/products

### LISTAR TODOS OS PRODUTOS POR CATEGORIA
GET http://localhost:3000/inventory/products?category_id=3b402dd5-a1fe-4b09-b7f8-6560d071abc5


### BUSCAR PRODUTO PELO ID
GET http://localhost:3000/inventory/products/b2cc3f53-f287-4380-99cf-33b576db8d4e


### ATUALIZAR PRODUTO
PUT http://localhost:3000/inventory/products/b2cc3f53-f287-4380-99cf-33b576db8d4e
Content-Type: application/json

{
    "name":"COCA COLA LATA 350ML",
    "category_id": "3b402dd5-a1fe-4b09-b7f8-6560d071abc5",
    "price": 3.50
}


### Criar uma order

POST http://localhost:3000/orders/
Content-Type: application/json

{
    "customer_id":"c7fa804e-0c31-4108-a059-f6412bf83f53",
    "customer_name":"Thiago Alves",
    "order_items": [
        {
            "product_id": "b2cc3f53-f287-4380-99cf-33b576db8d4e",
            "quantity": 2
        },
        {
            "product_id": "888c2b77-db34-4f7a-99e6-63851a0661f1",
            "quantity": 2
        },
        {
            "product_id": "a6da8219-5ffa-4cbd-9803-2debb6e9de94",
            "quantity": 1
        }
    ]
}

###
GET http://localhost:3000/orders/
Content-Type: application/json

